# Generated by Django 5.1.2 on 2024-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Completo:')),
                ('cargo_proyecto', models.TextField(verbose_name='Cargo de Proyecto')),
                ('celular', models.IntegerField(verbose_name='Cargo de Proyecto')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=50, verbose_name='Ingrese Departamentos'),
        ),
    ]
